# metapackage for a Mercurial "conda application" providing
# Mercurial with few extensions (hg-evolve and hg-git)

# inspired by
# https://github.com/conda-forge/mpi-feedstock
# https://github.com/conda-forge/spyder-feedstock

{% set version = "6.2.1" %}

package:
  name: mercurial-app
  version: {{ version }}

build:
  number: 0
  noarch: python

requirements:
  run:
    - mercurial =={{ version }}
    - hg-evolve
    - hg-git

test:
  commands:
    - hg --version

app:
  entry: hg
  icon: logo.png
  summary: Source control management tool
  own_environment: True

about:
  home: https://github.com/conda-forge/mercurial-app-feedstock
  license: GPL-2.0-or-later
  license_file: LICENSE.txt
  summary: Source control management tool

extra:
  recipe-maintainers:
    - paugier
