# metapackage for a Mercurial "conda application" providing
# Mercurial with few extensions (hg-evolve and hg-git)

# Note: hg-git is not yet available on conda-forge

# inspired by
# https://github.com/conda-forge/mpi-feedstock
# https://github.com/conda-forge/spyder-feedstock

{% set version = "5.4" %}

package:
  name: mercurial-app
  version: {{ version }}

build:
  number: 0
  skip: true  # [win and py3k]

requirements:
  run:
    - python
    - mercurial =={{ version }}
    - hg-evolve
    - hg-git
    - dulwich
    - ipaddress  # [py==27]
    # tmp, see https://github.com/conda-forge/urllib3-feedstock/issues/25
    - brotlipy

test:
  commands:
    - hg --version

app:
  entry: hg
  icon: logo.png
  summary: Source control management tool
  own_environment: True

about:
  home: https://github.com/conda-forge/mercurial-app-feedstock
  license: GPL-2.0-or-later
  license_file: LICENSE.txt
  summary: Source control management tool

extra:
  recipe-maintainers:
    - paugier
