# metapackage for a Mercurial "conda application" providing
# Mercurial with few extensions (hg-evolve and hg-git)

{% set version = "6.8.2" %}

package:
  name: mercurial-app
  version: {{ version }}

build:
  number: 1
  noarch: python

requirements:
  run:
    - python >={{ python_min }}
    - mercurial =={{ version }}
    - hg-evolve
    - hg-git
    - hg-setup

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
    - hg version -v
    - hg debuginstall
    - hg setup -h

app:
  entry: hg
  icon: logo.png
  summary: Source control management tool
  own_environment: True

about:
  home: https://github.com/conda-forge/mercurial-app-feedstock
  license: GPL-2.0-or-later
  license_file: LICENSE.txt
  summary: Source control management tool

extra:
  recipe-maintainers:
    - paugier
