travis:
  secure:
    BINSTAR_TOKEN: AoEwkvELIb1l+qOp49uKr+i40IMA7rrvWCfq0f5fwOLTrmK8u4LhJvEWS7QokW/G97pWah06zZuh3vR8dXG05OF9Cm2zgH39+hgcsXXLoYpHZmfWVN5vsivlbOYe8xAEKAdfd3ljaqveGe81zhFfEgJ1UPzJaFwwIeR+4ihRZabemHet6RXiYSmIn9gwi/fPEy1xUYhbgUOsuL/842SlaRqHWgfRPOfKx+KLOfppqCJtfy7OR2nm84AurTgKZMbin+ngXlujvy/7M1uc1XaHRz/N5WaiFVL9vfGYqj+2u10yg/9cI253RPo3yPsbdHVEyumiwSkrRpToh/C7moZSAHJjCEzk8BRRb8Yw8DUyOtCm16ona2qrxDVsGU5W9jIvXjnTcacf7k9BIaqKzNGYIJdpE/MU+ZfdsF8pZ4Wqe4hIFp9c+HEVO0oLH2dT13jOd+WX6L3R3WGd/Baij5Eatrvf+7X36ADUqOI3XSe39bf4SsNWRQaF0050vhhLYED7nby0EzjhPk/5HzDnRNWBjkPsWOP7nK5wZEuGdxYVOlBjQ3gtZSAjLLFkgBm8VffidGKaxy6xjyxa/gqV0GCOvRLg+D5g/WXmc6sbycy2oCa32votirWZL3WixAcVSxfanJVmO7eX/hHkw1R7sD6HbT4OMU3EVeTQ4rOZbgVHIfA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
