travis:
  secure:
    BINSTAR_TOKEN: gqFtFndkqfv1hSh2anjZlXjn5WUfGQ2nAC7TKCPABK9YDRCq4HdAvhr8H4/yCCwrrhxc7ERJd9fo8QvQimGrNXCSqaRfuZQ13GKUPcZc1bt+8Dlb5wbutr1vjf/FeUxjvrGJ/VOYxZIW35oeZpqDkyT+G4hTbrPDw8gfic2CMfbVHSUSf2Y43pkoeyvq3WXifZ/oLgWImK4t7NAApPZINHb9+El5OXu25AuGQsRytVysHlBTXgd9JnTjWnYEG+hdZ1GV/A3jJrQOzxRpaFpFIxlcMVKTeAYnIzjL3L42R0P+OFuylqhIohqHo1iNlWBbcEzKXTO/y6oIpxYdfeupC3BAWxBO8u6a0REp8dufANLwaUBFQxa9p6FjeG26yCrHrICLU54YSN4ipzoeAXSpp0hMG6+zZKAZyZu7DEBknY6UvuYrYl1xqRCS3aQG/w1NfTGNxp/tDqRQBu+Zxy8ds76aBWIQ5sOISTfqnMIsVHdfhSf5FP5YbJRQWAolE6i6IR4T+rVkjagmBrhpCuKoEdbZvR4RlNEYiZYI9RDdjPboiJRLgwbix5hIyA9CMzzGZHL7vm/P+aWxIyn4SVT70RZCQEHtpZ+AalDdCOMJktDSvgrNsBwf1ncFKlpxic8nKoFpXOa1xvM/AfxwafhfkxiIoj+z5e2/VADyAnWKYpg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
